export const dcaAbi = [
  {
    type: "function",
    name: "create",
    stateMutability: "payable",
    inputs: [
      { name: "tokenIn", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "totalAmount", type: "uint256" },
      { name: "slices", type: "uint32" },
      { name: "interval", type: "uint32" },
      { name: "slippageBps", type: "uint16" },
    ],
    outputs: [{ name: "id", type: "uint256" }],
  },
  {
    type: "function",
    name: "execute",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancel",
    stateMutability: "nonpayable",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "nextId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "ownerOrders",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ type: "uint256[]" }],
  },
  {
    type: "function",
    name: "remaining",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "orders",
    stateMutability: "view",
    inputs: [{ name: "id", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "tokenIn", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "amountPerSlice", type: "uint256" },
      { name: "slices", type: "uint32" },
      { name: "executed", type: "uint32" },
      { name: "interval", type: "uint32" },
      { name: "nextExec", type: "uint32" },
      { name: "slippageBps", type: "uint16" },
      { name: "cancelled", type: "bool" },
      { name: "nativeIn", type: "bool" },
      { name: "nativeOut", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "Created",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "tokenIn", type: "address", indexed: false },
      { name: "tokenOut", type: "address", indexed: false },
      { name: "total", type: "uint256", indexed: false },
      { name: "slices", type: "uint32", indexed: false },
      { name: "interval", type: "uint32", indexed: false },
    ],
  },
] as const;
